### ISSUE TITLE
Running Planarian lineages: preprocessing using Scanpy Notebook

### ISSUE THREAD

**Issue by ElHirad** [theislab/paga#3]
Hello. I've tried the Notebook. Everything went well until I got this:
```py
>>> sc.tl.paga(adata, groups='clusters')
running PAGA
    finished (0:00:02.02)
>>> paga_plot_params = dict(
...     legend_fontsize=5,
...     solid_edges='confidence_tree',
...     dashed_edges='confidence',
... root=0,
... layout='rt_circular',
...     node_size_scale=0.5,
...     node_size_power=0.9,
...     max_edge_width=0.7,
...     fontsize=3.5)
>>> sc.pl.paga_compare(adata, title='100% of data, tSNE and abstracted graph', **paga_plot_params, save='_100percent')                                                                                      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/scanpy/plotting/tools/paga.py", line 127, in paga_compare
    **paga_graph_params)
  File "/usr/local/lib/python3.7/dist-packages/scanpy/plotting/tools/paga.py", line 433, in paga
    adjacency_solid = adata.uns['paga'][solid_edges].copy()
KeyError: 'confidence_tree'
```

Where did I do wrong?

**Comment by falexwolf** [comment]
Oh sorry. Which notebook is this? It should be 'connectivity_tree' in any case. I can fix it if you show me the notebook.

**Comment by DuaaAlawad** [comment]
> Oh sorry. Which notebook is this? It should be 'connectivity_tree' in any case. I can fix it if you show me the notebook.

I have the same issue. Can you help us with this? 
thanks

**Comment by flying-sheep** [comment]
I think it’s this one: https://github.com/rajewsky-lab/planarian_lineages/blob/master/paga/planaria.ipynb

Please file a bug with them
